---
  - name: Mesos | Set apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: E56151BF
    tags:
      - mesos

  - name: Mesos | Add debian repo
    apt_repository:
      repo: "deb http://repos.mesosphere.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
      state: present
    tags:
      - mesos

  - name: Mesos | Install mesos
    apt:
      name: mesos
      state: present
    notify: restart zookeeper
    tags:
      - mesos

  - name: Mesos | Config Zookeeper
    template:
      src: "zk.j2"
      dest: "/etc/mesos/zk"
    notify: restart zookeeper
    tags:
      - mesos
