---
  - name: Deploy | Kick off marathon app
    uri: url=http://{{ mesos_master_nodes[0] }}:{{ app.exposed_port }}/v2/apps/{{ app.name }}-{{version}}
       method=PUT
       body='{{ lookup("template", "templates/marathon_app.json.j2") | to_json }}'
       HEADER_Content-Type="application/json"
       status_code=200,201,204
    tags:
      - deploy