---
  - name: Consul | Run registrator container
    docker_container:
      name: registrator
      image: gliderlabs/registrator
      state: started
      restart_policy: always
      network_mode: host
      volumes: /var/run/docker.sock:/tmp/docker.sock
      command: -ip {{ ansible_eth1.ipv4.address }} -cleanup consul://localhost:8500
    tags:
     - consul
     - consul-registrator

  - name: Consul | Make sure registrator is started at boot
    template: src=init_registrator.conf.j2 dest=/etc/init/consul-registrator.conf
    tags:
     - consul
     - consul-registrator