webmaster_mail_address: email@example.com
root_from_mail: email@example.com
root_domain: example.com
timezone: Europe/Amsterdam

app:
  name: clustering
  image_name: tradecloud/clustering
  exposed_port: 8080

sshd_configs:
  - {regexp: "^Protocol.*", line: "Protocol 2"}
  - {regexp: "^PermitRootLogin.*", line: "PermitRootLogin yes"}
  - {regexp: "^RSAAuthentication.*", line: "RSAAuthentication yes"}
  - {regexp: "^PubkeyAuthentication.*", line: "PubkeyAuthentication yes"}
  - {regexp: "^ChallengeResponseAuthentication.*", line: "ChallengeResponseAuthentication no"}
  - {regexp: "^PasswordAuthentication.*", line: "PasswordAuthentication yes"}
  - {regexp: "^MaxAuthTries.*", line: "MaxAuthTries 10"}

mesos_master_nodes:
  - 192.168.33.10

consul_server_nodes:
  - 192.168.33.10
  - 192.168.33.11

consul_encrypt: "P1VpASZkDyhon6/iZqt6Qg=="

consul_templates:
  frontendApp:
    src: /etc/nginx/sites-available/frontendApp.ctmpl
    dest: /etc/nginx/sites-available/frontendApp
    cmd: service nginx restart